export default {
    "user": {
        "name": "Antonino Cicala",
        "isLogged": false,
        "img": null,
        "email": "anto.cic.127@gmail.com",
        "phone": "+39 3295436315",
        "rule": "Jr full stack developer",
        "site_link": "https://portfolio-antocic.netlify.app/",
        "git_link": "https://github.com/AntoCic",
        "linkedin_link": "https://www.linkedin.com/in/antonino-cicala/",
        "description": "Sono una persona socievole e appassionata di tecnologia, con il desiderio di trasformare questa passione in una carriera professionale. Sin dai tempi della scuola, ho continuato a studiare e aggiornarmi costantemente, acquisendo competenze nella creazione di applicazioni, web app e script per microprocessori.",
        "location": "Sciacca, AG",
        "date": "1996-07-12",
        "technologies": [
            "HTML",
            "CSS",
            "JavaScript",
            "Vite",
            "Vue",
            "Sass",
            "Bootstrap",
            "Notion",
            "PHP",
            "Laravel",
            "MySQL",
            "GIT",
            "Github",
            "SQL",
            "Node",
            "npm",
            "VsCode",
            "Postman",
            "React",
            "Tailwind",
            "Firebase"
        ]
    },
    "experiences": [
        {
            "id": "7648af5c-f85a-4de8-9fd5-42087630ae53",
            "name": "Boolean",
            "description": "ho lavorato a molti progetti utilizzando tutti i linguaggi elencati nelle skills",
            "rule": "jr Full Stack Web Developer Trainee",
            "location": "Full remote",
            "priority": 0,
            "dateStart": "2024-01-23",
            "dateEnd": "2024-07-17"
        },
        {
            "id": "7b7a5edd-55ed-488e-b251-67cf17790baf",
            "name": "Verdura resort, Rocco Forte",
            "description": "Durante questo periodo, ho lavorato con contratti stagionali. Ho operato sia in team sia individualmente, ottenendo eccellenti risultati in termini di incassi.",
            "rule": "Bartender",
            "location": "Sciacca, AG",
            "priority": 0,
            "dateStart": "2020-08-01",
            "dateEnd": "2023-11-01"
        },
        {
            "id": "3dcf4d6f-2438-43f2-a053-ab140785669f",
            "name": "Soho House Barcelona",
            "description": "La Soho House e una Club House solo per clienti selezionati. Sicuramente la migliore skill che ho appreso e la conoscenza della lingua Spagnola ma è servito anche per definire l’inglese e fare nuove amicizie.",
            "rule": "Bartender",
            "location": "Barcelona, Spagna",
            "priority": 0,
            "dateStart": "2018-10-04",
            "dateEnd": "2019-12-16"
        },
        {
            "id": "6ddae9d7-e406-491e-8a8a-1050dd2ec84c",
            "name": "Oblix, The shard",
            "description": "Questo ristorante è situato al 32º piano del grattacielo più alto di Londra. Qui ho appreso il mestiere del bartender ad un livello avanzato e migliorato la mia conoscenza dell'inglese, interagendo strettamente con una clientela e colleghi di diverse nazionalità.",
            "rule": "Bartender",
            "location": "London, UK",
            "priority": 0,
            "dateStart": "2017-03-01",
            "dateEnd": "2018-06-01"
        },
        {
            "id": "388077d3-8ab7-4a4b-9023-df962a9ad48a",
            "name": "Signor Sassi",
            "description": "Lavoravo per questo ristorante italiano a Londra e nei mesi che sono stato là sono partito da assistente cameriere e sono finito a gestire la caffetteria.",
            "rule": "Commí-barback",
            "location": "London, UK",
            "priority": 0,
            "dateStart": "2016-09-01",
            "dateEnd": "2017-03-01"
        },
        {
            "id": "4017adb4-f13b-40ef-a971-eda8bcc305e1",
            "name": "Civil Defence",
            "description": "Controllavo la sicurezza di chi frequentava gli stabilimenti balneari marini. Sono capace ed esperto negli interventi di soccorso di chi si trova in situazione di pericolo in acqua.\n\n",
            "rule": "Assistente Bagnanti",
            "location": "Marsala, TP",
            "priority": 0,
            "dateStart": "2016-07-01",
            "dateEnd": "2016-08-31"
        },
        {
            "id": "7670a7ed-a427-4d40-a149-9306d2d79994",
            "name": "CLICK IT",
            "description": "Durante lo stage, ho appreso come smontare e rimontare computer, riconoscendo e sostituendo le componenti danneggiate.",
            "rule": "Stagista",
            "location": "Sciacca, AG",
            "priority": 0,
            "dateStart": "2014-04-01",
            "dateEnd": "2014-05-01"
        }
    ],
    "visiblePj": [
        {
            "id": "75534121-d337-4feb-b91c-2e6352d5dbfd",
            "visible": true,
            "name": "TripCicRem",
            "img": "https://raw.githubusercontent.com/AntoCic/travel-app/main/public/img/logo.png",
            "video": null,
            "site_link": "https://cic-travel-app.netlify.app/",
            "git_link": "https://github.com/AntoCic/travel-app",
            "description": "Sei alla ricerca di un modo semplice e intuitivo per organizzare i tuoi viaggi, tenere traccia dei tuoi ricordi e conservare le tue foto e le emozioni del momento? Sei nel posto giusto. Questo sito è stato creato utilizzando tecnologie all'avanguardia come VUE, Vite, Bootstrap, SASS, Firebase SDK e TomTom SDK. Ho sviluppato personalmente un template che semplifica e rende sicuro lo scambio di dati con il database in tempo reale di Firebase, facilitando la gestione dello storage e includendo una sezione dedicata per l'autenticazione e la registrazione tramite Google o con email e password. La gestione delle rotte è affidata a Vue Router, con miglioramenti che automatizzano i redirect, mentre un sistema di validazione integrato, basato su Vue e Bootstrap, consente di validare i form con poche righe di codice. Il backend è gestito da Netlify Function Serverless, che, grazie a oggetti predefiniti come 'router' e 'firebase', permette di creare rapidamente chiamate personalizzate o automatiche al Realtime Database o allo storage.Inoltre, il sito offre la possibilità di visualizzare mappe dettagliate delle varie attività attraverso il TomTom SDK. Questo progetto non è solo uno strumento per organizzare e tenere traccia delle tue vacanze, ma è anche una piattaforma su cui sto migliorando le mie competenze con tutte le tecnologie citate e affinando le mie capacità logiche.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 1,
            "dateStart": "2024-08-12",
            "dateEnd": null,
            "technologies": [
                "Vue",
                "Vite",
                "Bootstrap",
                "Sass",
                "Firebase",
                "JavaScript",
                "HTML"
            ],
            "shortDescription": "Sei alla ricerca di un modo semplice e intuitivo per organizzare i tuoi viaggi, tenere traccia dei tuoi ricordi e conservare le tue foto e le emozioni del momento? Sei nel posto giusto. Questo sito è stato creato utilizzando "
        },
        {
            "id": "13cc50ec-4918-40f4-be96-67166e93e9b1",
            "visible": true,
            "name": "TextFacade",
            "img": "https://raw.githubusercontent.com/AntoCic/test_Tecnico_Deploy/main/logo.png",
            "video": null,
            "site_link": "https://test-tecnico-ub.netlify.app/",
            "git_link": "https://github.com/AntoCic/AntoninoCicala_Test_tecnico",
            "description": "Il progetto è realizzato utilizzando il design pattern Facade per gestire la logica di lettura e analisi dei file. È sviluppato in Node.js e utilizza i pacchetti esterni Express e Multer. Questo progetto è un'applicazione web che permette di caricare file di testo locali o di fornire URL di file di testo per analizzarli e ottenere:\n• il numero totale di parole nel file\n• il numero di lettere nel file\n• il numero di spazi nel file\n• le parole che si ripetono più di 10 volte e indicare il numero di volte in cui si ripetono.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 3,
            "dateStart": "2024-07-27",
            "dateEnd": null,
            "technologies": [
                "Node",
                "Express",
                "JavaScript",
                "Bootstrap"
            ],
            "shortDescription": "Il progetto è realizzato utilizzando il design pattern Facade per gestire la logica di lettura e analisi dei file. È sviluppato in Node.js e utilizza i pacchetti esterni Express e Multer. Questo progetto è un'applicazione web"
        },
        {
            "id": "79d00d27-9149-473f-aed7-7e2f7544c8ac",
            "visible": true,
            "name": "WatchFlick",
            "img": "https://raw.githubusercontent.com/AntoCic/watchflick/main/public/logo.png",
            "video": null,
            "site_link": "https://watchflick.netlify.app/",
            "git_link": "https://github.com/AntoCic/watchflick",
            "description": "Questo sito è stato creato per mettere alla prova le conoscenze acquisite su React e Tailwind. Il suo scopo è fornire una libreria completa di film e serie TV. Ho utilizzato React come framework front-end, Redux per gestire lo store, React Router per la gestione delle rotte, Tailwind CSS per lo stile, e l'API di The Movie Database (TMDb) per i contenuti.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 2,
            "dateStart": "2024-07-24",
            "dateEnd": null,
            "technologies": [
                "React",
                "Tailwind",
                "HTML",
                "CSS",
                "JavaScript",
                "Vite",
                "Node",
                "npm"
            ],
            "shortDescription": "Questo sito è stato creato per mettere alla prova le conoscenze acquisite su React e Tailwind. Il suo scopo è fornire una libreria completa di film e serie TV. Ho utilizzato React come framework front-end, Redux per gestire l"
        },
        {
            "id": "f633cd18-2941-48c0-b1aa-9174754f9e86",
            "visible": true,
            "name": "StayHub",
            "img": "https://raw.githubusercontent.com/Andrea-Calligari/boolbnb-team-6/main/front_office_vue/public/img/logo.svg",
            "video": "https://raw.githubusercontent.com/Andrea-Calligari/boolbnb-team-6/main/StayHub.mp4",
            "site_link": null,
            "git_link": "https://github.com/Andrea-Calligari/boolbnb-team-6",
            "description": "Il sito è stato progettato per replicare la struttura di Airbnb, includendo un sistema di autenticazione front-end, la possibilità di creare nuovi appartamenti o modificarne di esistenti, e ricerche avanzate nel database basate sul raggio da un punto sulla mappa e su determinate caratteristiche. È prevista la possibilità di acquistare promozioni tramite carta di credito per aumentare la visibilità degli appartamenti, nonché la visualizzazione di statistiche per ogni appartamento riguardanti la correlazione tra visualizzazioni e giorni. Il progetto è stato realizzato utilizzando Laravel per il backend, Vue per il frontend, le API di TomTom per la gestione e la valorizzazione degli indirizzi, BrainTree per la validazione dei pagamenti e Chart.js per la visualizzazione delle statistiche.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 1,
            "dateStart": "2024-07-17",
            "dateEnd": null,
            "technologies": [
                "Vue",
                "Sass",
                "Bootstrap",
                "Vite",
                "PHP",
                "Laravel"
            ],
            "shortDescription": "Il sito è stato progettato per replicare la struttura di Airbnb, includendo un sistema di autenticazione front-end, la possibilità di creare nuovi appartamenti o modificarne di esistenti, e ricerche avanzate nel database basa"
        },
        {
            "id": "1ce78a57-0334-40b0-8354-88b5fb32e103",
            "visible": true,
            "name": "Portfolio",
            "img": "https://portfolio-antocic.netlify.app/img/logo.png",
            "video": null,
            "site_link": "https://portfolio-antocic.netlify.app/",
            "git_link": "https://github.com/AntoCic/portfolio",
            "description": "Il portfolio è interamente modificabile tramite una pagina di Notion. Utilizzando le API fornite da\nNotion",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 2,
            "dateStart": "2024-06-24",
            "dateEnd": null,
            "technologies": [
                "CSS",
                "HTML",
                "JavaScript",
                "Vue",
                "Sass",
                "Bootstrap",
                "Vite",
                "Notion"
            ],
            "shortDescription": "Il portfolio è interamente modificabile tramite una pagina di Notion. Utilizzando le "
        },
        {
            "id": "30d7a607-bba7-4cb5-a1e4-23fbcf19f8f6",
            "visible": true,
            "name": "Warrior",
            "img": "https://raw.githubusercontent.com/MarinaLasorsa/game-creator/main/resources/img/utility/logo.png",
            "video": "https://raw.githubusercontent.com/MarinaLasorsa/game-creator/main/warrior.mp4",
            "site_link": null,
            "git_link": "https://github.com/MarinaLasorsa/game-creator",
            "description": "Progetto realizzato per mettere alla prova le conoscenze di base acquisite su Laravel, focalizzandosi sulla gestione delle operazioni CRUD e sull'autenticazione. Un'esperienza pratica che ha permesso di consolidare le competenze nello sviluppo web con Laravel. ",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 3,
            "dateStart": "2024-05-31",
            "dateEnd": "2024-06-18",
            "technologies": [
                "Laravel",
                "PHP",
                "Sass",
                "Bootstrap",
                "MySQL"
            ],
            "shortDescription": "Progetto realizzato per mettere alla prova le conoscenze di base acquisite su Laravel, focalizzandosi sulla gestione delle operazioni CRUD e sull'autenticazione. Un'esperienza pratica che ha permesso di consolidare le compete"
        },
        {
            "id": "ad7399ad-2a3e-4319-addb-9ff2d659f8aa",
            "visible": true,
            "name": "Cicmind",
            "img": "https://cicmind.netlify.app//img/fav.png",
            "video": null,
            "site_link": "https://cicmind.netlify.app/",
            "git_link": "https://github.com/AntoCic/MPP_mastermind",
            "description": "Mastermind è un gioco di logica tra due giocatori: uno (PC) che fa da \"codificatore\" e crea un codice segreto, e l'altro (TU) che fa da \"decodificatore\" e cerca di indovinare il codice entro un numero limitato di tentativi.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 3,
            "dateStart": "2024-03-25",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript",
                "Bootstrap",
                "Sass"
            ]
        },
        {
            "id": "f6878308-70d3-4304-b7ee-806a6364663d",
            "visible": true,
            "name": "Cicbomb",
            "img": "https://cicbomb.netlify.app/img/fav.png",
            "video": null,
            "site_link": "https://cicbomb.netlify.app",
            "git_link": "https://github.com/AntoCic/MPP_campominato",
            "description": "Campo minato, noto anche come Minesweeper, è un gioco di logica in cui l'obiettivo è scoprire tutte le caselle non minate senza far esplodere le mine.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 3,
            "dateStart": "2024-03-21",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript",
                "Bootstrap"
            ]
        },
        {
            "id": "09deba9e-e929-4281-8cc3-a5aa0497f333",
            "visible": true,
            "name": "CocktailDB",
            "img": "https://ac-cocktaildb.netlify.app/img/logo.png",
            "video": null,
            "site_link": "https://ac-cocktaildb.netlify.app/",
            "git_link": "https://github.com/AntoCic/cocktailDB",
            "description": "Uno dei primi siti che ho realizzato per testare le conoscenze acquisite su JavaScript e sull'utilizzo delle chiamate API",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 3,
            "dateStart": "2023-11-28",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript"
            ]
        },
        {
            "id": "ad70290b-60b0-4f74-ad66-c98f8950d57b",
            "visible": true,
            "name": "Curriculum",
            "img": "https://antonino-cicala.netlify.app/img/logo.png",
            "video": null,
            "site_link": "https://antonino-cicala.netlify.app/",
            "git_link": "https://github.com/AntoCic/Curriculum",
            "description": "il promo sito creato per mostrare i dati del Curriculum",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 3,
            "dateStart": "2023-07-05",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript"
            ]
        }
    ],
    "template": [
        {
            "id": "aed5312a-48b0-4ead-b9ed-6e91cd5de1b7",
            "visible": true,
            "name": "Vue, firebase, Bootstrap",
            "img": "https://raw.githubusercontent.com/AntoCic/TEMP_vue-bootstrap-firebase/main/public/img/logo.png",
            "video": null,
            "site_link": "https://temp-vue-bootstrap-firebase.netlify.app",
            "git_link": "https://github.com/AntoCic/TEMP_vue-bootstrap-firebase",
            "description": "Questo template offre una struttura chiara e ben organizzata per gestire l'accesso, la registrazione e il caricamento dei contenuti, assicurando un'esperienza utente fluida e intuitiva. Utilizza un sistema di storage reattivo per gestire i dati in modo efficiente ed è dotato di Vue Router per una navigazione senza interruzioni tra le pagine. Include anche i link a Google Icons CSS per una facile integrazione delle icone nel progetto.\nInoltre, il template integra funzionalità avanzate per garantire una maggiore sicurezza e ottimizzare l'interazione con il Realtime Database. Utilizza file di validazione come ",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 10,
            "dateStart": "2024-08-13",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript",
                "Vite",
                "Vue",
                "Sass",
                "Bootstrap",
                "Node",
                "npm",
                "Firebase"
            ],
            "shortDescription": "Questo template offre una struttura chiara e ben organizzata per gestire l'accesso, l"
        },
        {
            "id": "5a6afcbe-1b9b-4bc9-9d17-c4ed35e84823",
            "visible": true,
            "name": "Vue, Bootstrap",
            "img": "https://raw.githubusercontent.com/AntoCic/TEMP_vue_bootstrap/main/public/img/logo.png",
            "video": null,
            "site_link": "https://temp-vue-bootstrap.netlify.app/",
            "git_link": "https://github.com/AntoCic/TEMP_vue_bootstrap",
            "description": "Questo template base include Vue, Bootstrap e Sass, e utilizza un sistema di storage reattivo per gestire i dati in modo efficiente. È dotato di Vue Router per una navigazione fluida tra le pagine e comprende i link ai Google Icons CSS per una facile integrazione di icone nel progetto. Inoltre, il template offre opzioni per l'integrazione con Netlify e le sue funzionalità serverless, e fornisce spiegazioni dettagliate su come eseguire il deploy del progetto. Con queste caratteristiche, il template è progettato per facilitare la creazione e la distribuzione di applicazioni web moderne e scalabili.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 10,
            "dateStart": "2024-08-09",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript",
                "Vite",
                "Vue",
                "Sass",
                "Bootstrap"
            ],
            "shortDescription": "Questo template base include Vue, Bootstrap e Sass, e utilizza un sistema di storage "
        },
        {
            "id": "0d8cdcb8-2edf-4c51-9ac4-bdf5bb0383db",
            "visible": true,
            "name": "html, css, js",
            "img": "https://raw.githubusercontent.com/AntoCic/TEMP_html-css-js/main/src/img/logo.png",
            "video": null,
            "site_link": "https://temp-html-css-js.netlify.app/",
            "git_link": "https://github.com/AntoCic/TEMP_html-css-js",
            "description": "Questo template fornisce una struttura chiara per sviluppare una pagina web utilizzando HTML, CSS e JavaScript. Inoltre, offre opzioni per l'integrazione con Netlify e le sue funzioni serverless, e include spiegazioni dettagliate sul processo di deploy.",
            "utility": null,
            "rule": "Full stack",
            "location": null,
            "priority": 10,
            "dateStart": "2024-08-08",
            "dateEnd": null,
            "technologies": [
                "HTML",
                "CSS",
                "JavaScript"
            ],
            "shortDescription": "Questo template fornisce una struttura chiara per sviluppare una pagina web utilizzan"
        },
        {
            "id": "bd32005f-9bad-4058-ab9f-292351c38b03",
            "visible": true,
            "name": "Template-react",
            "img": "https://raw.githubusercontent.com/AntoCic/template-react/main/public/logo.png",
            "video": null,
            "site_link": "https://template-react-antocic.netlify.app",
            "git_link": "https://github.com/AntoCic/template-react",
            "description": "Template React con Redux e Tailwind CSS, ancora da completare.",
            "utility": null,
            "rule": null,
            "location": null,
            "priority": 10,
            "dateStart": "2024-07-24",
            "dateEnd": null,
            "technologies": [
                "Vite",
                "React",
                "Tailwind",
                "JavaScript",
                "CSS"
            ]
        }
    ]
}